import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="cyberpunk" lang="en">
      
      <body>
        <div>
          <Navbar />
        </div>
        {children} 
        <Analytics />
        <div>
          <Footer />
        </div>
      </body>
    
    </html>
  );
}
