import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "JVC | Cycle53 *",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html data-theme="abyss" lang="en">
      <body className="max-h-screen flex flex-col">
        <Navbar />
        
        {children} 
        <div>
        </div>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
